### PR TITLE
Pin future in RequestSender

### LINKED ISSUE #38: Unable to use RequestReplier in async task
This sample code gives an error:
```rust
#[tokio::main]
async fn main() {
    let ctx = tmq::Context::new();
    let handle = tokio::task::spawn(async move {
        let mut socket = tmq::reply(&ctx).bind("tcp://0.0.0.0:5001").unwrap();
        loop {
            let (msg, req) = socket.recv().await.unwrap();
            socket = req.send(msg).await.unwrap();
        }
    });
    handle.await.unwrap();
}
```
Output:
```
error: future cannot be sent between threads safely
   --> src/main.rs:4:37
    |
4   |       let handle = tokio::task::spawn(async move {
    |  _____________________________________^
5   | |         let mut socket = tmq::reply(&ctx).bind("tcp://0.0.0.0:5001").unwrap();
6   | |         loop {
7   | |             let (msg, req) = socket.recv().await.unwrap();
8   | |             socket = req.send(msg).await.unwrap();
9   | |         }
10  | |     });
    | |_____^ future created by async block is not `Send`
    |
    = help: within `RequestReceiver`, the trait `Sync` is not implemented for `*mut c_void`
note: future is not `Send` as this value is used across an await
   --> /home/bemyak/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tmq-0.3.2/src/socket_types/request_reply.rs:54:79
    |
54  |         let msg = futures::future::poll_fn(|cx| self.inner.multipart_recv(cx)).await?;
    |                                            ---------------------------------- ^^^^^^ - `|cx| self.inner.multipart_recv(cx)` is later dropped here
    |                                            |                                  |
    |                                            |                                  await occurs here, with `|cx| self.inner.multipart_recv(cx)` maybe used later
    |                                            has type `[closure@RequestReceiver::recv::{closure#0}::{closure#0}]` which is not `Send`
note: required by a bound in `tokio::spawn`
   --> /home/bemyak/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/task/spawn.rs:163:21
    |
163 |         T: Future + Send + 'static,
    |                     ^^^^ required by this bound in `spawn`
```

`Publish` and `Subscribe` seem to work fine.

Any hints on how to fix this?

### PR DESCRIPTION
**Pull request by bemyak**
+ Bump deps
+ Remove deprecated feature

Fixes #38

### CODE REVIEW

**Comment by willstott101** [comment]
Any particular reason to target 1.26 not 1.28 of Tokio in this? Perhaps it wasn't released

**Comment by bemyak** [comment]
@willstott101, yes, `1.26` was the latest version when I submitted this PR, there is no reason not to bump it again.

**Comment by cetra3** [comment]
Since this is a semver change can you bump the version number up?

**Comment by bemyak** [comment]
@cetra3, it's a minor version bump, right? I don't think the public API has changed.

**Comment by bemyak** [comment]
I've split this PR into separate commits and bumped the minor version

**Comment by cetra3** [comment]
@bemyak the version of `zmq` has had a major revision in this PR, from `0.9` to `0.10`, so I would consider this semver breaking.  It's not that it's a big issue, just need to bump to `0.4.0`

**Comment by willstott101** [comment]
`zmq = ">=0.9.2"` already pulled in `0.10` for us I think anyway

**Comment by bemyak** [comment]
OK, bumped it to `0.4.0`

**Comment by cetra3** [comment]
@bemyak For semver versions in rust < `1.0.0`  i.e, `0.1` `0.2` etc.. the minor version is treated as a major version & so something like `>= 0.9.2` will only include `0.9.x` versions

**Comment by bemyak** [comment]
@cetra3, right. I've rewritten the commit message to remove the confusion.

Also `>=` is the [default Cargo behavior](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html):

> The string "0.1.12" is a version requirement. Although it looks like a specific version of the time crate, it actually specifies a range of versions […]
>
> Here are some more examples of version requirements […]
> ```
> 0.2.3  :=  >=0.2.3, <0.3.0
> ```

Is there anything else I can do here?

**Comment by cetra3** [comment]
Thanks! I've published this as `0.4.0`

**Pull request merged**
